# Checkpoint: cp-001
id: "cp-001"
type: checkpoint
created: "2026-01-26T00:55:56Z"

trigger:
  type: manual
  source_id: null  # Between actions
  source_type: action

description: "Test checkpoint"

context:
  goal_id: g-20250126-add-user-auth
  plan_id: p-001-database
  task_id: t-001-user-model
  action_id: null  # Between actions

snapshot:
  files:
    - path: "src/models/User.ts"
      hash: "sha256:cfb7388a4dc3c9f2d22fa30dd81008b7006b59ab18556f83affd9996aa4a826f"
      size: 21
      content_ref: "snapshot/src/models/User.ts"

  git:
    available: false
    branch: null
    commit_hash: null
    dirty_files: []
    stash_ref: null

restoration:
  can_restore: true
  method: file_copy
  would_affect:
    - path: "src/models/User.ts"
      checkpoint_hash: "sha256:cfb7388a4dc3c9f2d22fa30dd81008b7006b59ab18556f83affd9996aa4a826f"

status: active
restored_at: null
restored_by: null
