# CHECKPOINT SCHEMA
# A checkpoint captures system state for reversibility
# Stored in .threads/checkpoints/{checkpoint-id}/checkpoint.yaml

id: null  # Format: cp-{NNN}
type: checkpoint
created: null

# What triggered this checkpoint
trigger:
  type: null  # manual | before_action | on_task_complete | on_plan_complete | scheduled
  source_id: null  # ID of action/task/plan that triggered it
  source_type: null  # action | task | plan

description: null  # Human-readable description

# Location in hierarchy
context:
  goal_id: null
  plan_id: null
  task_id: null
  action_id: null

# What's captured
snapshot:
  # Files captured
  files: []
  # - path: "src/models/User.ts"
  #   hash: "sha256:abc123..."
  #   size: 1234
  #   content_ref: "snapshots/cp-001/src_models_User.ts"  # Path to stored content

  # Git state (if in a git repo)
  git:
    available: false
    branch: null
    commit_hash: null
    dirty_files: []
    stash_ref: null  # If we stashed changes

# Restoration info
restoration:
  can_restore: true
  method: null  # file_copy | git_reset | git_stash_pop

  # What would be affected by restoration
  would_affect: []
  # - path: "src/models/User.ts"
  #   current_hash: "sha256:def456..."
  #   would_restore_to: "sha256:abc123..."

  # Dependencies (other checkpoints that must be restored first/after)
  depends_on: []
  would_invalidate: []  # Later checkpoints that would be invalidated

# Status
status: active  # active | restored | superseded | pruned

restored_at: null
restored_by: null  # "human" or "system"
