# Project Context
# Accumulated knowledge about this project
# This context is inherited by all goals, plans, tasks, and actions

discovered:
  # Technology stack
  stack: []
  # Example:
  # - "Next.js 14 with App Router"
  # - "TypeScript in strict mode"
  # - "PostgreSQL database"

  # Project patterns
  patterns: []
  # Example:
  # - "Services live in src/services/"
  # - "React Context for global state"
  # - "Zod schemas for validation"

  # Constraints and requirements
  constraints: []
  # Example:
  # - "Must support Node 18+"
  # - "No external authentication services"
  # - "All API routes must be authenticated"

# Key files discovered during exploration
key_files:
  entry_points: []
  config_files: []
  frequently_modified: []

# Decisions made at project level
decisions: []
# Example:
# - id: "d-001"
#   date: "2024-01-26"
#   decision: "Use httpOnly cookies for auth tokens"
#   rationale: "More secure than localStorage, prevents XSS token theft"

# Learnings accumulated across all work
learnings: []
# Example:
# - id: "l-001"
#   date: "2024-01-26"
#   learning: "The AuthContext expects synchronous initialization"
#   source: "Discovered while implementing OAuth"
#   still_valid: true
